### ISSUE TITLE
Missing File in Psytrance Project

### ISSUE THREAD

**Issue by thelonious** [polarity/bitwig-projects#1]
Hello,

When I open the Psytrance.bwproject file, Bitwig 4.3 Beta 4 complains about a missing wavetable file name "Transistor Square.wt". I've been looking online for while, but I can't seem to locate this file. Can you direct me to where I might find this file?

Thanks!

**Comment by stephane303** [comment]
Yes I've have asked the same question on Facebook, I am not sure how to fix this also

**Comment by stephane303** [comment]
I believe that when the wavetable is not found, it defaults back to "Standard Four"

So if you manually set it to "Standard Four" and save you should be good. I did that and I think it's the same as the original

**Comment by thelonious** [comment]
Thanks @stephane303! I'll give that a try
